/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package reportes;

import java.awt.*;
import java.text.ParsePosition;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.*;


/**
 *
 * @author LIC. SALVADOR CRUZ DURÁN
 */
public class Grafico extends javax.swing.JFrame {

    /**
     * Creates new form Grafico
     */
    public Grafico() {
        initComponents();
        PanelFondo F = new PanelFondo(); // Creamos el objeto F de tipo Panel Fondo
        this.add(F, BorderLayout.CENTER);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelFecha1 = new javax.swing.JLabel();
        jFormattedTextFecha1 = new javax.swing.JFormattedTextField();
        jLabelFecha2 = new javax.swing.JLabel();
        jFormattedTextFecha2 = new javax.swing.JFormattedTextField();
        jButtonCargar = new javax.swing.JButton();
        jLabelLote = new javax.swing.JLabel();
        jTextFieldLote = new javax.swing.JTextField();
        jButtonReporte = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FRUCASA - Guayabas");
        setAlwaysOnTop(true);
        setIconImage(new ImageIcon(getClass().getResource("/iconos/frucasa.png")).getImage());
        setResizable(false);

        jLabelTitulo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTitulo.setText("REPORTE GRAFICO");

        jLabelFecha1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFecha1.setText("DE LA FECHA:");
        jLabelFecha1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        try {
            jFormattedTextFecha1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFecha1.setName(""); // NOI18N

        jLabelFecha2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelFecha2.setText("A LA FECHA:");
        jLabelFecha2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        try {
            jFormattedTextFecha2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButtonCargar.setText("Cargar");
        jButtonCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCargarActionPerformed(evt);
            }
        });

        jLabelLote.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelLote.setText("NUMERO DE LOTE:");
        jLabelLote.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTextFieldLote.setName(""); // NOI18N

        jButtonReporte.setText("GENERAR REPORTE GRAFICO");
        jButtonReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReporteActionPerformed(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NUMERO DE LOTE", "FECHA", "MARCA", "REGISTRO DE HUERTO", "PRODUCTO"
            }
        ));
        jTable1.setCellSelectionEnabled(true);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setGridColor(new java.awt.Color(240, 240, 240));
        jTable1.setName(""); // NOI18N
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelLote)
                    .addComponent(jLabelFecha1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldLote, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelFecha2)
                        .addGap(10, 10, 10)
                        .addComponent(jFormattedTextFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCargar))
                    .addComponent(jButtonReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFecha1)
                    .addComponent(jLabelFecha2)
                    .addComponent(jButtonCargar)
                    .addComponent(jFormattedTextFecha2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLote)
                    .addComponent(jTextFieldLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonReporte))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jButtonCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCargarActionPerformed

        try{
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date fecha1 = sdf.parse(this.jFormattedTextFecha1.getText(), new ParsePosition(0));
            Date fecha2 = sdf.parse(this.jFormattedTextFecha2.getText(), new ParsePosition(0));
            if (fecha1.before(fecha2) || fecha1.equals(fecha2));
            else JOptionPane.showMessageDialog(Grafico.this, "revisar fecha");

            //establecer el modelo al JTable
            DefaultTableModel modelo = new DefaultTableModel();
            this.jTable1.setModel(modelo);

            //Conexion a la base de datos
            DriverManager.registerDriver(new com.mysql.jdbc.Driver());

            Connection conexion;
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/fru","frucasa","frucasa09");

            //Para ejecutar la consulta
            Statement s = conexion.createStatement();
            try (ResultSet rs = s.executeQuery("SELECT lotes.num_fol AS 'NUMERO DE LOTE', lotes.fecha AS 'FECHA', productores.mar_prod AS 'MARCA', huertos.reg_hue AS 'REGISTRO DE HUERTO', productos.des_pro AS 'PRODUCTO' FROM productos INNER JOIN (productores INNER JOIN ((huertos INNER JOIN lotes ON huertos.cve_hue = lotes.cve_hue) INNER JOIN loteparcial ON lotes.num_fol = loteparcial.lote) ON productores.cve_prod = huertos.cve_prod) ON productos.cve_pro = lotes.cve_pro WHERE ( lotes.fecha BETWEEN '"+this.jFormattedTextFecha1.getText()+"' AND '"+this.jFormattedTextFecha2.getText()+"');")) {
                ResultSetMetaData rsMd = rs.getMetaData();

                //Cantidad de columnas que tiene la consulta
                int cantidadColumnas = rsMd.getColumnCount();

                //Establecer como cabeceras el nombre de las columnas
                for(int i = 1; i <= cantidadColumnas; i++){
                    modelo.addColumn(rsMd.getColumnLabel(i));
                }

                //Creando las filas para el jTable
                while(rs.next()){
                    Object[] fila = new Object[cantidadColumnas];
                    for (int i = 0; i < cantidadColumnas; i++){
                        fila[i]=rs.getObject(i+1);
                    }
                    modelo.addRow(fila);
                }
            }
            conexion.close();
        }catch(SQLException e){
            JOptionPane.showMessageDialog(Grafico.this, e.getMessage());
        }

        // Final del codigo contenido en el boton cargar
    }//GEN-LAST:event_jButtonCargarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     
        DefaultTableModel mi=(DefaultTableModel)this.jTable1.getModel();
//creamos una variable que va a contener la fila seleccionada de la tabla
int i =jTable1.getSelectedRow();
int c = 0;

//hacemos una condicion de que si la varialbe i es igual a - es que no se ha seleccionado ninguna 
//fila,

//creamos nuestras varialbes que va a contener los datos de la fila seleccionado en este caso
//nom va a tener el dato que se encuentra en la fila (i),recuerda que esa variable es la fila //seleccionada,columna 0,que tiene el campo nombre me imagino,y hacemos lo mismo con los otros.getValueAt Obetemos el valor que se encuentra en la tabla indicando la fila y columna.
//haciendo un Casting a String ese valor.
String lote=(String) this.jTable1.getValueAt(i, c).toString();
this.jTextFieldLote.setText(lote);  



//Espero haberte ayudado. Lo puedes hacer en un boton que diga Modificas.
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

  
    private void jButtonReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReporteActionPerformed

      
        Reporte r;
        r = new Reporte();
      r.mostrarReporte();
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Grafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Grafico().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCargar;
    private javax.swing.JButton jButtonReporte;
    private javax.swing.JFormattedTextField jFormattedTextFecha1;
    private javax.swing.JFormattedTextField jFormattedTextFecha2;
    private javax.swing.JLabel jLabelFecha1;
    private javax.swing.JLabel jLabelFecha2;
    private javax.swing.JLabel jLabelLote;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldLote;
    // End of variables declaration//GEN-END:variables
}
